### PR TITLE
[ADD] sale_report_hide_zero_discount: Hides the total discount in sales reports when it is zero.

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
@ValentinVinagre 
[T-6001]

### CODE REVIEW

**Review by HaraldPanten — CHANGES_REQUESTED** [review]
This module shouldn't be in this repository.

The correct one would be sy-sale-reporting.

Why don't we publish this module directly in OCA (sale-reporting repository)?

**Comment by angelgarciadelachica** [comment]
@HaraldPanten I'm not quite sure it should be in sy-sale-reporting. It is true that it is only for sales-reporting, but it is an extension of the sale_discount_display_amount module from the sale-workflow repository.

On the other hand, I think it's a very simple module to push it to OCA, could an IMP of sale_discount_display_amount be better?

What do you think @ValentinVinagre?

**Comment by ValentinVinagre** [comment]
@angelgarciadelachica podría ser perfectamente un IMP de ese módulo. Si quieres lo puedes llevar a OCA.

**Comment by HaraldPanten** [comment]
I agree. That would be nice as an improvement of the original module. THX

**Comment by ValentinVinagre** [comment]
@angelgarciadelachica cierro el PR y te dejo la rama. Borra la rama una vez la tengas en OCA, etc. Merci

**Pull request closed without merging**
